### ISSUE TITLE
macroquad-particles crate does not compile with latest macroquad (from crates.io).

### ISSUE THREAD

**Issue by profan** [not-fl3/macroquad#831]
### Description
Currently if you use macroquad and macroquad-particles in a project with the latest crates.io versions, you'll end up with a compilation error regarding ambiguity between `macroquad::texture::RenderPass` and `macroquad::miniquad::RenderPass`.

On my project this looks something like this:
```
   --> /home/profan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-particles-0.2.1/src/lib.rs:680:13
    |
680 |             post_processing_pass,
    |             ^^^^^^^^^^^^^^^^^^^^ expected `macroquad::texture::RenderPass`, found `macroquad::miniquad::RenderPass`
    |
    = note: `macroquad::miniquad::RenderPass` and `macroquad::texture::RenderPass` have similar names, but are actually distinct types
note: `macroquad::miniquad::RenderPass` is defined in crate `miniquad`
   --> /home/profan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/miniquad-0.4.6/src/graphics.rs:564:1
    |
564 | pub struct RenderPass(usize);
    | ^^^^^^^^^^^^^^^^^^^^^
note: `macroquad::texture::RenderPass` is defined in crate `macroquad`
   --> /home/profan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.4.13/src/texture.rs:347:1
    |
347 | pub struct RenderPass {
```

Definitely caused by 52cac9b08f2d8beba8c9ba8a0e487487be8447bf ... which is my own past change.

**Reproduction**
1. Create a new rust project.
2. Add a dependency on macroquad 0.4.x.
3. Add a dependency on macroquad-particles 0.2.1.
4. Try to compile the project.

My guess is that macroquad-particles just needs to be republished with a version bump, as macroquad works fine with the git version directly, when not going through crates.io for the dependency.

**Comment by profan** [comment]
Solved by [47918d9](https://github.com/not-fl3/macroquad/commit/47918d97c04a5bd01a3f544d1a3eef1c62d5faa4), thanks @not-fl3 :)
