### ISSUE TITLE
Any plans to update docker image for android build?

### ISSUE THREAD

**Issue by rax35** [not-fl3/macroquad#978]
Currently the docker image uses rust v1.79, which results in the following error trying to build with latest macroquad (v0.4.14):

```
error[E0658]: floating point arithmetic is not allowed in constant functions
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.4.14/src/color.rs:108:13
    |
108 |             r as f32 / 255.,
    |             ^^^^^^^^^^^^^^^
    |
    = note: see issue #57241 <https://github.com/rust-lang/rust/issues/57241> for more information
```
(Multiple similar errors truncated)

This occurs in both a normal `cargo build` and `cargo quad-apk` inside the container.

Does anyone know if manually doing the setup works or is `cargo-quad-apk` itself outdated?

Also, is there any plans to update the docker image?
